name = "my-next-app"
compatibility_date = "2024-07-20"
compatibility_flags = ["nodejs_compat"]

[env.preview.vars]
BASIC_USER=admin
BASIC_PASS=admin
ENV=develop

[env.production.vars]
ENV=production

